# Generated by Django 3.2.3 on 2021-06-02 11:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
